wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714399737.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 23
      - 35
      4: 3.11.8
      5: 0.16.5
      8:
      - 1
      - 5
      13: linux-x86_64
